name: location
description: A Flutter plugin to easily handle realtime location in iOS and Android. Provides settings for optimizing performance or battery.
version: 2.3.5
author: Guillaume Bernos <guillaume.bernos@gmail.com>
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.lyokone.location
    pluginClass: LocationPlugin

dependencies:
  flutter:
    sdk: flutter
