name: location
description: A Flutter plugin for location with Callbacks.
version: 1.1.4
author: Guillaume Bernos
homepage: https://github.com/Lyokone/flutterlocation

flutter:
  plugin:
    androidPackage: com.lyokone.location
    pluginClass: LocationPlugin

dependencies:
  flutter:
    sdk: flutter
