name: location
description: A Flutter plugin for location with Callbacks.
version: 2.0.0
author: Guillaume Bernos
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.lyokone.location
    pluginClass: LocationPlugin

dependencies:
  flutter:
    sdk: flutter
