name: location_platform_interface
description: A common platform interface for the location plugin.
version: 2.3.0
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
