name: location_platform_interface
description: A common platform interface for the location plugin.
version: 3.1.0
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.5

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  leancode_lint: ^3.0.0
  mockito: ^5.0.0
