name: location_web
description: The web implementation of the location plugin.
version: 6.0.1
homepage: https://github.com/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
issue_tracker: https://github.com/Lyokone/flutterlocation/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.1.0
  location_platform_interface: ^6.0.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      web:
        pluginClass: LocationWebPlugin
        fileName: location_web.dart
