name: location
description: This librarie aims at providing you a simple way to get the user location without thinking about permission.
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
version: 5.0.0-dev.4

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: location_android
      ios:
        default_package: location_ios
      # linux:
      #   default_package: location_linux
      macos:
        default_package: location_macos
      web:
        default_package: location_web
      # windows:
      #   default_package: location_windows

dependencies:
  flutter:
    sdk: flutter
  location_android: ^5.0.0-dev.2
  location_ios: ^5.0.0-dev.3
  # location_linux:
  #   path: ../location_linux
  location_macos: ^5.0.0-dev.2
  location_platform_interface: ^5.0.0-dev.2
  location_web: ^5.0.0-dev.2
  # location_windows:
  #   path: ../location_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.0
