name: location
description: Get the location of your user
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: location_android
      # ios:
      #   default_package: location_ios
      # linux:
      #   default_package: location_linux
      # macos:
      #   default_package: location_macos
      # web:
      #   default_package: location_web
      # windows:
      #   default_package: location_windows

dependencies:
  flutter:
    sdk: flutter
  location_android:
    path: ../location_android
  # location_ios:
  #   path: ../location_ios
  # location_linux:
  #   path: ../location_linux
  # location_macos:
  #   path: ../location_macos
  # location_platform_interface:
  #   path: ../location_platform_interface
  # location_web:
  #   path: ../location_web
  # location_windows:
  #   path: ../location_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.0
