name: location
description: A Flutter plugin to easily handle realtime location in iOS and Android. Provides settings for optimizing performance or battery.
version: 4.4.0
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.lyokone.location
        pluginClass: LocationPlugin
      ios:
        pluginClass: LocationPlugin
      macos:
        pluginClass: LocationPlugin
      web:
        default_package: location_web

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface: ^2.3.0
  location_web: ^3.1.1
dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
