name: location
description: A Flutter plugin to easily handle realtime location in iOS and Android. Provides settings for optimizing performance or battery.
version: 3.2.2
author: Guillaume Bernos <guillaume@bernos.dev>
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.lyokone.location
        pluginClass: LocationPlugin
      ios:
        pluginClass: LocationPlugin
      macos:
        pluginClass: LocationPlugin
      web:
        default_package: location_web

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface: ^1.1.0
    # path: ../location_platform_interface
  location_web: ^1.0.1
    # path: ../location_web
  meta: ^1.0.5

dev_dependencies:
  async: ^2.0.8
  flutter_test:
    sdk: flutter
  mockito: 3.0.0
  plugin_platform_interface: ^1.0.3
  test: ^1.3.0
