name: location_ios
description: iOS implementation of the location plugin
homepage: https://docs.page/Lyokone/flutterlocation~version-5
repository: https://github.com/Lyokone/flutterlocation
version: 5.0.0-dev.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: location
    platforms:
      ios:
        pluginClass: LocationPlugin
        dartPluginClass: LocationIOS

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface: ^5.0.0-dev.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^3.1.5
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.0
